### PR TITLE
Switch to new repo

### PR DESCRIPTION
**Pull request by imranpopz**

### CODE REVIEW

**Review by manjotsidhu — COMMENTED** [review]
LGTM

**Comment by manjotsidhu** [comment]
@AndroiableDroid Just check if more things need to be fixed for 3.0

**Comment by AndroiableDroid** [comment]
Not needed https://github.com/PitchBlackRecoveryProject/manifest_pb/blob/android-9.0/twrp-extras.xml#L13-L15 check

**Comment by imranpopz** [comment]
Add that commit in android-8.1 manifest too

**Comment by DelightReza** [comment]
https://github.com/PitchBlackRecoveryProject/manifest_pb/blob/android-8.1/twrp-extras.xml#L10

**Comment by imranpopz** [comment]
> Not needed https://github.com/PitchBlackRecoveryProject/manifest_pb/blob/android-9.0/twrp-extras.xml#L13-L15 check

android-8.1 manifest doesn't fetch vendor_utils

**Pull request closed without merging**
